name: Bug Report
description: Report a bug
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        **Before making a bug report, please:**
        - Check if you are using the latest available version of the project.
        - Search existing issues to avoid duplicates.
  - type: input
    id: project
    attributes:
      label: Project
      description: The project which this bug report is for.
      placeholder: Name of the project (ex. EasyZoom)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and detailed description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: information
    attributes:
      label: Information
      description: Information about your Minecraft version and loader.
      value: |
        - Minecraft version (ex. 1.20.1):
        - Loader (ex. Forge):
        - Mod version (ex. 1.0.0):
        Any other screenshots or information that might be helpful.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: A step-by-step guide on how to reproduce the bug.
      value: |
        - 1.
        - 2.
        - 3.
    validations:
      required: true
