name: Feature Request
description: Suggest a new feature or improvement
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: >
        **Before making a feature request, please search existing denied or
        planned requests to avoid duplicates.**
  - type: input
    id: project
    attributes:
      label: Project
      description: The project which this feature request is for.
      placeholder: Name of the project (ex. EasyZoom)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you want added in detail.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Information
      description: Share any extra details or references that might help understand your suggestion.
